name: 'IND'
on:
  schedule:
    - cron: '25 19 * * *'  # UTC 19:25 = KST 04:25
  workflow_dispatch:

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 최근 커밋만 가져오기
      
      - name: Get and Submit New Posts
        run: |
          # 최근 24시간 내의 커밋에서 추가된 _posts 파일 찾기
          SINCE_TIME=$(date -d "24 hours ago" -u +"%Y-%m-%d %H:%M:%S")
          
          echo "Finding posts added since: $SINCE_TIME"
          
          # 새로 추가된 포스트 파일 찾기
          NEW_FILES=$(git log --since="$SINCE_TIME" --name-only --diff-filter=A --format="" "_posts/*.md")
          
          if [ -n "$NEW_FILES" ]; then
            echo "Found new posts:"
            echo "$NEW_FILES"
            
            # URL 배열 생성
            URL_LIST="["
            while IFS= read -r file; do
              if [ -n "$file" ]; then
                # 파일명에서 URL 경로 생성
                FILENAME=$(basename "$file")
                URL_PATH=$(echo "$FILENAME" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' | sed 's/\.md$//' | sed 's/--/-/g' | sed 's/-$//')
                URL="https://shopshop2.github.io/shopping/$URL_PATH/"
                URL_LIST="$URL_LIST\"$URL\","
              fi
            done <<< "$NEW_FILES"
            URL_LIST="${URL_LIST%,}]"
            
            echo "Submitting URLs to IndexNow:"
            echo "$URL_LIST"
            
            response=$(curl -s -w "\nHTTP Status: %{http_code}" -X POST "https://api.indexnow.org/indexnow" \
              -H "Content-Type: application/json" \
              -d "{
                \"host\": \"shopshop2.github.io\",
                \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
                \"urlList\": $URL_LIST,
                \"keyLocation\": \"https://shopshop2.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
              }")
            
            echo "IndexNow API Response:"
            echo "$response"
            
            if echo "$response" | grep -q "HTTP Status: 200"; then
              echo "✅ URLs successfully submitted to search engines!"
            else
              echo "❌ Error submitting URLs. Please check the response above."
              exit 1
            fi
          else
            echo "No new posts found in the last 24 hours"
          fi

      - name: Report status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ IndexNow submission completed successfully"
          else
            echo "❌ IndexNow submission failed"
          fi
          echo "Workflow completed at: $(date)"
