name: 'IndexNow'
on:
  schedule:
    - cron: '25 19 * * *'  # UTC 19:25 = KST 04:25
  workflow_dispatch:

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Debug Info
        run: |
          echo "GitHub Context:"
          echo "  Repository: ${{ github.repository }}"
          echo "  Ref: ${{ github.ref }}"
          echo "  Event: ${{ github.event_name }}"
          
          echo "Time Info:"
          echo "  UTC: $(date -u)"
          echo "  KST: $(TZ='Asia/Seoul' date)"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get changed files and submit URLs
        run: |
          CHANGED_FILES=$(git log --since="24 hours ago" --name-only --diff-filter=A --format="" "_posts/*.md")
          
          if [ ! -z "$CHANGED_FILES" ]; then
            echo "Changed files found:"
            echo "$CHANGED_FILES"
            
            URL_LIST="["
            declare -A seen_urls
            
            for file in $CHANGED_FILES; do
              FILENAME=$(basename "$file")
              # 날짜 제거, .md 제거, 이중 대시 처리
              URL_PATH=$(echo "$FILENAME" | 
                        sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' | 
                        sed 's/\.md$//')
              URL="https://shopshop2.github.io/shopping/$URL_PATH/"
              
              if [ -z "${seen_urls[$URL]}" ]; then
                seen_urls[$URL]=1
                URL_LIST="$URL_LIST\"$URL\","
                echo "Processing: $URL"
              fi
            done
            
            URL_LIST="${URL_LIST%,}]"
            
            response=$(curl -s -w "\nHTTP Status: %{http_code}" -X POST "https://api.indexnow.org/indexnow" \
              -H "Content-Type: application/json" \
              -d "{
                \"host\": \"shopshop2.github.io\",
                \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
                \"urlList\": $URL_LIST,
                \"keyLocation\": \"https://shopshop2.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
              }")
            
            echo "IndexNow API Response:"
            echo "$response"
            
            if echo "$response" | grep -q "HTTP Status: 200"; then
              echo "✅ URLs successfully submitted to search engines!"
            else
              echo "❌ Error submitting URLs. Please check the response above."
              exit 1
            fi
          else
            echo "No new posts found in the last 24 hours"
          fi

      - name: Report status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ IndexNow submission completed successfully"
          else
            echo "❌ IndexNow submission failed"
          fi
          echo "Workflow completed at: $(date)"
