name: 'IND'
on:
  schedule:
    - cron: '25 19 * * *'  # UTC 19:25 = KST 04:25
  workflow_dispatch:

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Debug Info
        run: |
          echo "Time Info:"
          echo "  UTC: $(date -u)"
          echo "  KST: $(TZ='Asia/Seoul' date)"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get changed files and submit URLs
        run: |
          # 임시 파일 생성
          TEMP_URL_FILE="urls.txt"
          > "$TEMP_URL_FILE"
          
          # 새로 추가된 파일 찾기
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              FILENAME=$(basename "$file")
              # .md 확장자 제거 및 날짜 부분 제거
              URL_PATH=$(echo "$FILENAME" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' | sed 's/\.md$//')
              
              # URL 생성 및 저장
              echo "https://shopshop2.github.io/shopping/$URL_PATH/" >> "$TEMP_URL_FILE"
            fi
          done < <(git log --since="24 hours ago" --name-only --diff-filter=A --format="" "_posts/*.md")
          
          if [ -s "$TEMP_URL_FILE" ]; then
            echo "Found new posts:"
            cat "$TEMP_URL_FILE"
            
            # URLs를 JSON으로 변환
            URL_LIST="["
            while IFS= read -r url; do
              URL_LIST="$URL_LIST\"$url\","
            done < "$TEMP_URL_FILE"
            URL_LIST="${URL_LIST%,}]"
            
            # JSON 요청 파일 생성
            REQUEST_FILE="request.json"
            echo "{
              \"host\": \"shopshop2.github.io\",
              \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
              \"urlList\": $URL_LIST,
              \"keyLocation\": \"https://shopshop2.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
            }" > "$REQUEST_FILE"
            
            # API 요청
            response=$(curl -s -w "\nHTTP Status: %{http_code}" \
              -X POST "https://api.indexnow.org/indexnow" \
              -H "Content-Type: application/json" \
              -d @"$REQUEST_FILE")
            
            echo "IndexNow API Response:"
            echo "$response"
            
            if echo "$response" | grep -q "HTTP Status: 200"; then
              echo "✅ URLs successfully submitted to search engines!"
            else
              echo "❌ Error submitting URLs. Please check the response above."
              exit 1
            fi
          else
            echo "No new posts found in the last 24 hours"
          fi

      - name: Report status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ IndexNow submission completed successfully"
          else
            echo "❌ IndexNow submission failed"
          fi
          echo "Workflow completed at: $(date)"
