name: 'IND'
on:
 schedule:
   - cron: '25 19 * * *'  # UTC 19:25 = KST 04:25
 workflow_dispatch:

jobs:
 submit-urls:
   runs-on: ubuntu-latest
   permissions:
     contents: read
   steps:
     - name: Debug Info
       run: |
         echo "GitHub Context:"
         echo "  Repository: ${{ github.repository }}"
         echo "  Ref: ${{ github.ref }}"
         echo "  Event: ${{ github.event_name }}"
         echo "Time Info:"
         echo "  UTC: $(date -u)"
         echo "  KST: $(TZ='Asia/Seoul' date)"

     - name: Checkout repository
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Check Directory Structure
       run: |
         pwd
         ls -la
         echo "Posts directory content:"
         ls -la _posts/ || echo "_posts directory not found"

     - name: Get changed files and submit URLs
       run: |
         # 디버그용 출력 추가
          echo "Listing all recent commits:"
          git log --since="24 hours ago" --oneline
          
          echo "Listing all files in recent commits:"
          git log --since="24 hours ago" --name-only --pretty=format:
          
          # 24시간 이내 변경된 마크다운 파일 찾기
          CHANGED_FILES=$(git diff --name-only HEAD@{24.hours.ago} HEAD | grep "^_posts/.*\.md$" || true)
         
         if [ ! -z "$CHANGED_FILES" ]; then
           echo "Changed files found:"
           echo "$CHANGED_FILES"
           
           URL_LIST="["
           declare -A seen_urls
           
           for file in $CHANGED_FILES; do
             FILENAME=$(basename "$file")
             URL_PATH=$(echo "$FILENAME" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' | sed 's/--/-/g' | sed 's/\.md$//' | sed 's/-$//')
             URL="https://shopshop2.github.io/shopping/$URL_PATH/"
             
             if [ -z "${seen_urls[$URL]}" ]; then
               seen_urls[$URL]=1
               URL_LIST="$URL_LIST\"$URL\","
               echo "Processing: $URL"
             fi
           done
           
           URL_LIST="${URL_LIST%,}]"
           echo "Sample URL format:"
           echo $URL_LIST | grep -o '"https://[^"]*"' | head -n 1
           
           response=$(curl -s -w "\nHTTP Status: %{http_code}" -X POST "https://api.indexnow.org/indexnow" \
             -H "Content-Type: application/json" \
             -d "{
               \"host\": \"shopshop2.github.io\",
               \"key\": \"87ae650ca3ec4b2daec3bee8fa7ac2e3\",
               \"urlList\": $URL_LIST,
               \"keyLocation\": \"https://shopshop2.github.io/87ae650ca3ec4b2daec3bee8fa7ac2e3.txt\"
             }")
           
           echo "IndexNow API Response:"
           echo "$response"
           
           if echo "$response" | grep -q "HTTP Status: 200"; then
             echo "URLs successfully submitted to search engines!"
           else
             echo "Error submitting URLs. Please check the response above."
             exit 1
           fi
         else
           echo "No markdown files found in _posts directory in the last 24 hours"
         fi

     - name: Report status
       if: always()
       run: |
         if [ "${{ job.status }}" = "success" ]; then
           echo "✅ IndexNow submission completed successfully"
         else
           echo "❌ IndexNow submission failed"
         fi
         echo "Workflow completed at: $(date)"
