name: 'IndexNow with Git'
on:
  schedule:
    - cron: '25 19 * * *'  # UTC 19:25 = KST 04:25
  workflow_dispatch:

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Process New Posts
        run: |
          SINCE_TIME=$(date -d "24 hours ago" -u +"%Y-%m-%d %H:%M:%S")
          echo "Finding posts added since: $SINCE_TIME"
          
          # URLs를 임시 파일에 저장
          URL_FILE="urls.txt"
          > "$URL_FILE"
          
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              # markdown 파일에서 제목 추출
              TITLE=$(grep -m 1 "^title:" "$file" | cut -d'"' -f2 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
              if [ -z "$TITLE" ]; then
                # 파일명에서 제목 생성
                FILENAME=$(basename "$file")
                TITLE=$(echo "$FILENAME" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' | sed 's/\.md$//')
              fi
              
              # URL 슬러그 생성
              SLUG=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9가-힣]/-/g' | sed 's/-\+/-/g' | sed 's/^-//' | sed 's/-$//')
              
              URL="https://shopshop2.github.io/shopping/${SLUG}/"
              echo "$URL" >> "$URL_FILE"
              echo "Generated URL: $URL"
            fi
          done < <(git log --since="$SINCE_TIME" --name-only --diff-filter=A --format="" "_posts/*.md")
          
          if [ -s "$URL_FILE" ]; then
            # URLs를 JSON 배열로 변환
            URL_LIST="["
            while IFS= read -r url; do
              URL_LIST="${URL_LIST}\"${url}\","
            done < "$URL_FILE"
            URL_LIST="${URL_LIST%,}]"
            
            echo "Submitting URLs to IndexNow:"
            echo "$URL_LIST"
            
            # 파일을 통해 curl 실행
            echo "{
              \"host\": \"shopshop2.github.io\",
              \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
              \"urlList\": $URL_LIST,
              \"keyLocation\": \"https://shopshop2.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
            }" > request.json
            
            response=$(curl -s -w "\nHTTP Status: %{http_code}" \
              -X POST "https://api.indexnow.org/indexnow" \
              -H "Content-Type: application/json" \
              -d @request.json)
            
            echo "IndexNow API Response:"
            echo "$response"
            
            if echo "$response" | grep -q "HTTP Status: 200"; then
              echo "✅ URLs successfully submitted!"
            else
              echo "❌ Error submitting URLs"
              exit 1
            fi
          else
            echo "No new posts found in the last 24 hours"
          fi

      - name: Report status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ IndexNow submission completed successfully"
          else
            echo "❌ IndexNow submission failed"
          fi
          echo "Workflow completed at: $(date)"
