name: 'IndexNow'
on:
 schedule:
   - cron: '25 19 * * *'  # UTC 19:25 = KST 04:25
 workflow_dispatch:

jobs:
 submit-urls:
   runs-on: ubuntu-latest
   permissions:
     contents: read
   steps:
     - name: Debug Info
       run: |
         echo "Time Info:"
         echo "  UTC: $(date -u)"
         echo "  KST: $(TZ='Asia/Seoul' date)"

     - name: Checkout repository
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Get changed files and submit URLs
       run: |
         echo "🔍 Finding changed files..."
         CHANGED_FILES=$(find _posts/ -name "*.md" -mtime -1 -type f)
         
         if [ ! -z "$CHANGED_FILES" ]; then
           FILE_COUNT=$(echo "$CHANGED_FILES" | wc -l)
           echo "Found $FILE_COUNT files in last 24 hours"
           
           URL_LIST="["
           URL_COUNT=0
           
           while IFS= read -r file; do
             if [ ! -z "$file" ]; then
               FILENAME=$(basename "$file")
               URL_PATH=$(echo "$FILENAME" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' | sed 's/--/-/g' | sed 's/\.md$//' | sed 's/-$//')
               URL="https://shopshop2.github.io/shopping/$URL_PATH/"
               
               if [ $URL_COUNT -gt 0 ]; then
                 URL_LIST="$URL_LIST,"
               fi
               URL_LIST="$URL_LIST\"$URL\""
               ((URL_COUNT++))
               echo "Processing $URL_COUNT/$FILE_COUNT: $URL"
             fi
           done <<< "$CHANGED_FILES"
           
           echo "Total URLs to submit: $URL_COUNT"
           URL_LIST="$URL_LIST]"
           
           echo "Submitting URLs to search engines..."
           response=$(curl -s -w "\nHTTP Status: %{http_code}" -X POST "https://api.indexnow.org/indexnow" \
           -H "Content-Type: application/json" \
           -d "{
             \"host\": \"shopshop2.github.io\",
             \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
             \"urlList\": $URL_LIST,
             \"keyLocation\": \"https://shopshop2.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
           }")
           
           echo "IndexNow API Response:"
           echo "$response"
           
           if echo "$response" | grep -q "HTTP Status: \(200\|202\)"; then
             echo "✅ Successfully submitted $URL_COUNT URLs!"
           else
             echo "❌ Error submitting URLs"
             exit 1
           fi
         else
           echo "No files modified in the last 24 hours"
         fi
