name: 'IndexNow'
on:
  schedule:
    - cron: '25 19 * * *'  # UTC 19:25 = KST 04:25
  workflow_dispatch:  # 수동 실행 옵션 유지

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Debug Info
        run: |
          echo "GitHub Context:"
          echo "  Repository: ${{ github.repository }}"
          echo "  Ref: ${{ github.ref }}"
          echo "  Event: ${{ github.event_name }}"
          
          echo "Time Info:"
          echo "  UTC: $(date -u)"
          echo "  KST: $(TZ='Asia/Seoul' date)"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Directory Structure
        run: |
          pwd
          ls -la
          echo "Posts directory content:"
          ls -la _posts/ || echo "_posts directory not found"

      - name: Get changed files and submit URLs
        run: |
          CHANGED_FILES=$(find _posts/ -name "*.md" -mtime -1 -type f)
          
          if [ ! -z "$CHANGED_FILES" ]; then
            echo "Changed files found:"
            FILE_COUNT=$(echo "$CHANGED_FILES" | wc -l)
            echo "Found $FILE_COUNT files in last 24 hours"
            
            URL_LIST="["
            URL_COUNT=0
            PROCESSED_URLS=""
            
            for file in $CHANGED_FILES; do
              FILENAME=$(basename "$file")
              URL_PATH=$(echo "$FILENAME" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' | sed 's/--/-/g' | sed 's/\.md$//' | sed 's/-$//')
              URL="https://guidekey.github.io/shopping/$URL_PATH/"
              
              # 중복 URL 체크
              if [[ ! $PROCESSED_URLS =~ $URL ]]; then
                if [ $URL_COUNT -gt 0 ]; then
                  URL_LIST="$URL_LIST,"
                fi
                URL_LIST="$URL_LIST\"$URL\""
                PROCESSED_URLS="$PROCESSED_URLS $URL"
                ((URL_COUNT++))
                echo "Processing: $URL"
              fi
            done
            
            URL_LIST="$URL_LIST]"
            echo "Sample URL format:"
            echo $URL_LIST | grep -o '"https://[^"]*"' | head -n 1
            echo "Total URLs to submit: $URL_COUNT"
            
            response=$(curl -s -w "\nHTTP Status: %{http_code}" -X POST "https://api.indexnow.org/indexnow" \
            -H "Content-Type: application/json" \
            -d "{
              \"host\": \"guidekey.github.io\",
              \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
              \"urlList\": $URL_LIST,
              \"keyLocation\": \"https://guidekey.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
            }")
            
            echo "IndexNow API Response:"
            echo "$response"
            
            if echo "$response" | grep -q "HTTP Status: \(200\|202\)"; then
              echo "$URL_COUNT URLs successfully submitted to search engines!"
            else
              echo "Error submitting URLs. Please check the response above."
              exit 1
            fi
          else
            echo "No markdown files found in _posts directory in the last 24 hours"
          fi

      - name: Report status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ IndexNow submission completed successfully"
          else
            echo "❌ IndexNow submission failed"
          fi
          echo "Workflow completed at: $(date)"
