name: 'Test Workflow'

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo time
        run: |
          echo "Current time: $(date)"
